version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./page/:/usr/share/nginx/html
      - ./nginx/:/etc/nginx/

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123123
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data/:/var/lib/mysql
    